#pragma config(Sensor, S1,     sonic,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     line_tracker,   sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Motor,  motorA,          drive_left,    tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          drive_right,   tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//file for all functions
#include "mse110_lab_1_v3_functions.c"

task main()
{
	detectStartingColor();
///*
	//if the line is blue run the blue function
	if (starting_colour == BLUE) {
		blueLine();
	}
	//if the line is green run the green function
	else if (starting_colour == GREEN) {
		greenLine();
	}
	//beep if the colour was no determined
	else {
		playSound(soundBeepBeep);
	}
//*/
}
